"""lead unsubscribed flag

Revision ID: 0a0b03545610
Revises: fe3d571796d9
Create Date: 2026-07-31 13:54:13.541378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0b03545610'
down_revision: Union[str, Sequence[str], None] = 'fe3d571796d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('unsubscribed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'unsubscribed')
    # ### end Alembic commands ###
