"""lead research icp signals

Revision ID: 7715f4d90838
Revises: e031ffea680f
Create Date: 2026-07-31 10:51:52.573851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7715f4d90838'
down_revision: Union[str, Sequence[str], None] = 'e031ffea680f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_research', sa.Column('website_quality_score', sa.Integer(), nullable=True))
    op.add_column('lead_research', sa.Column('website_issues', sa.JSON(), nullable=True))
    op.add_column('lead_research', sa.Column('estimated_team_size', sa.String(), nullable=True))
    op.add_column('lead_research', sa.Column('icp_fit_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_research', 'icp_fit_score')
    op.drop_column('lead_research', 'estimated_team_size')
    op.drop_column('lead_research', 'website_issues')
    op.drop_column('lead_research', 'website_quality_score')
    # ### end Alembic commands ###
