"""lead qualification reason

Revision ID: fe3d571796d9
Revises: 7715f4d90838
Create Date: 2026-07-31 12:04:13.375754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3d571796d9'
down_revision: Union[str, Sequence[str], None] = '7715f4d90838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('qualification_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'qualification_reason')
    # ### end Alembic commands ###
